#!/bin/bash

# $RANDOM returns a different random integer at each invocation.
# Nominal range: 0 - 32767 (signed 16-bit integer).

MAXCOUNT=$1
count=1

while [ "$count" -le $MAXCOUNT ]     
do
  number=$RANDOM
  echo $number
  let "count += 1"  
done
